# Dependencies
markdown:         redcarpet
highlighter:      pygments
highlighter:      true

# Permalinks
permalink:        pretty

# Setup
title:            studioidefix
tagline:          'Here be Dragons'
description:      'here be dragons'
url:              http://studioidefix.com

author:
  name:           'Anish Bhatt'
  url:            https://github.com/anish

paginate:         5

# Custom vars
version:          1.0.5

github:
  repo:           https://github.com/poole/hyde
